// This file is generated by Slice Machine. Update with care!

import CtaButton from './CtaButton';
import Features from './Features';
import Hero from './Hero';
import ImageAndText from './ImageAndText';
import TesteSlice from './TesteSlice';

export {
	CtaButton,
	Features,
	Hero,
	ImageAndText,
	TesteSlice,
};

export const components = {
	cta_button: CtaButton,
	features: Features,
	hero: Hero,
	image_and_text: ImageAndText,
	teste_slice: TesteSlice,
};
